### ISSUE TITLE
Currently README and the structure of the repo are a mess.

### ISSUE THREAD

**Issue by Miecznik42** [zchwang/OnionNet-2#10]
README contains multiple spelling mistakes in the names of files in the provided usage examples, some of the files have outright changed names and/or locations, some useful files are missing, and installation steps create issues due to not specified versions of packages.

Recommendation: 
Try running all the described steps like a new user would, and fix issues as they appear. Well constructed README should allow a new user to use the tool without much tinkering, and this is simply not the case as of now.

**Comment by zchwang** [comment]
The README and repository have been updated, and you can refer to the updated tutorial.
