### ISSUE TITLE
Error in generating features file

### ISSUE THREAD

**Issue by Fatima-Aslam** [zchwang/OnionNet-2#3]
Hi,
I'm trying to execute generate_features.py file but I'm getting error "OSError: The topology is loaded by filename extension, and the detected ".pd" format is not supported. Supported topology formats include ".pdb", ".pdb.gz", ".h5", ".lh5", ".prmtop", ".parm7", ".prm7", ".psf", ".mol2", ".hoomdxml", ".gro", ".arc", ".hdf5" and ".gsd"."
Can you please guide me, how to reolve it?
![error](https://user-images.githubusercontent.com/86885366/189080805-9d7897b5-5b64-44f5-bbe6-3302d1fd8ca7.PNG)
Thanks

**Comment by zchwang** [comment]
Hi, 

The error message says that your input file suffix is ".pd" instead of ".pdb", so you should check the suffix of your input structure file.

Best regards

**Comment by Fatima-Aslam** [comment]
Thank you for your reply.
But I recheck the input file, its contains .pdb 
I take .pdb complexes from OnionNet and prepare its .dat file
![directory](https://user-images.githubusercontent.com/86885366/189187083-c3cc9c3b-9cfe-46d8-90bd-2021f0497fa5.PNG)
![input](https://user-images.githubusercontent.com/86885366/189187122-08ea7686-1498-4836-8c0d-8c6f3c15a0f5.PNG)
Please guide me, how to create input file?
Thank you!

**Comment by Fatima-Aslam** [comment]
Thank you for your reply.
But I recheck the input file, its contains .pdb
I take .pdb complexes from OnionNet and prepare its .dat file
Please guide me, how to create an input file?
Thank you!

**Comment by zchwang** [comment]
Hi,

I probably guessed what caused it, maybe there are differences in text operations between windows and linux systems. Still, I think you might use some other tricks for reading files, maybe you could try changing line 186 in generate_features.py to the following:
                                   inputs = [x.strip() for x in lines]

Best regards,
Zechen

**Comment by Fatima-Aslam** [comment]
Thank you soo much for your reply. It's so kind of you.
I will chcek it and let you know.

**Comment by Fatima-Aslam** [comment]
Thank you for your advice. Error has been removed and features file has been successfully generated. But when I concat features files and PKa file another error comes.
that is:
File "concat_features_pKa.py", line 44, in <module>
    new_values.append(dict_[i] + true_dict[i])
KeyError: '10gs_complex.pdb'

![error2](https://user-images.githubusercontent.com/86885366/189337906-e3bbe778-ed4f-4103-a1b9-ddfbc1de6c23.PNG)
Can you please suggest me anything to resolve it?
Thank you!

**Comment by zchwang** [comment]
Hi, 

The input file for this tutorial, such as all_complexes_pKa.csv, needs to be prepared by yourself. This file provides the affinity value pKd of the complex. The format of the file can be referred to datasets/all_pKa_cplx.csv. Therefore, you need to set the input file according to the actual situation of your task, and at the same time ensure that the index in output_features.csv is consistent with that in all_complexes_pKa.csv.

Best regards, 
Zechen

**Comment by Fatima-Aslam** [comment]
Thank you soo much. Errors has been fixed now. Thanks for your corporation.
I want to know about files, train features pka & valid features pka.
Can both of these files be same?
Thanks

**Comment by zchwang** [comment]
For deep learning, the training set and validation set should not be the same. Therefore, there should be no overlapping between the two sets. You might be able to first understand the role of training and validation sets in the training process, and then you could easily understand the case here.
