### ISSUE TITLE
Where to find complex.pdb?

### ISSUE THREAD

**Issue by GattiMh** [zchwang/OnionNet-2#4]
Hello,

I'm trying to run the tutorial files but I can't find the complex.pdbs files. I've seen the script prepare_PDB_file.sh but not sure how it is supposed to work. Any help?

Working on mac btw.

Many thanks

**Comment by zchwang** [comment]
Hi,

I uploaded the 1a30_complex.pdb file in OnionNet-2/tutorials/samples/1a30, you can refer to this file to generate the protein-ligand complex file yourself. 

Best regards,
Zechen

**Comment by GattiMh** [comment]
Thank you. I'm trying to run the `concat_features.pka.py` as shown in the example. After generating the features using the previous step, I run:

`python concat_features_pKa.py -inp_features output_features.csv -inp_true datasets/all_pKa_cplx.csv -out output_features_pKa.csv` and I get:


`Start Now ...
Traceback (most recent call last):
  File "concat_features_pKa.py", line 44, in <module>
    new_values.append(dict_[i] + true_dict[i])
KeyError: '/Users/opt/OnionNet-2/tutorials/samples/1a30/1a30_complex.pdb'`

Thanks

**Comment by zchwang** [comment]
Hi，
    This script (concat_features_pKa.py)  is used to horizontally concatenate features and affinity labels together, so the labels of the corresponding samples need to be queried from the label dictionary. This operation should ensure that the keys are consistent.  For example, the file "/datasets/all_pKa_cplx.csv" contains the affinity data of protein-ligand, the pKd value of the first sample (1xd1/1xd1_cplx.pdb), so the key should be guaranteed to be "1xd1/1xd1_cplx.pdb" when querying the value from the dictionary.
    Of cource, I recommend that you can use your own way to input features and labels into the neural network. The paradigm provided here is to concatenate features and labels into a "csv" file. When using them, the features and labels can be obtained by df.values[:, :-1] and df.values[:, -1] respectively.

Best regards
