### ISSUE TITLE
Error when train OnionNet-2 with shells=30

### ISSUE THREAD

**Issue by JonasLi-19** [zchwang/OnionNet-2#8]
shells=30, the total features=5040, so the features_pKa csv has 5042 columns.
5040 = 63*80 = 60*84

`python train.py -train_file train_features_pKa.csv -valid_file valid_features_pKa.csv -shape 63 80 1 -n_features 30`
`python train.py -train_file train_features_pKa.csv -valid_file valid_features_pKa.csv -n_features 30 -shape 60 84 1`

BUT it always raises error like:
```
Training set loaded ...
Validating set loaded ...
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    X_train_std = scaler.fit_transform(X_train).reshape([-1] + args.shape)
ValueError: cannot reshape array of size 491580 into shape (63,80,1)
```

**Comment by zchwang** [comment]
The dimension of X_train should be [B, 21*8*N], B represents the number of samples, 21*8 is the number of residue-atom pairs, and N is the number of shells. I guess this error is caused by wrong data dimensions.
